# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IndividualLayerWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(285, 608)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_Base = QtWidgets.QFrame(Form)
        self.frame_Base.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Base.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Base.setObjectName("frame_Base")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_Base)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_y = QtWidgets.QLabel(self.frame_Base)
        self.label_y.setObjectName("label_y")
        self.gridLayout_2.addWidget(self.label_y, 2, 0, 1, 1)
        self.horizontalSlider_x = QtWidgets.QSlider(self.frame_Base)
        self.horizontalSlider_x.setMaximum(100)
        self.horizontalSlider_x.setProperty("value", 50)
        self.horizontalSlider_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_x.setObjectName("horizontalSlider_x")
        self.gridLayout_2.addWidget(self.horizontalSlider_x, 1, 0, 1, 1)
        self.label_x = QtWidgets.QLabel(self.frame_Base)
        self.label_x.setObjectName("label_x")
        self.gridLayout_2.addWidget(self.label_x, 0, 0, 1, 1)
        self.label_z = QtWidgets.QLabel(self.frame_Base)
        self.label_z.setObjectName("label_z")
        self.gridLayout_2.addWidget(self.label_z, 4, 0, 1, 1)
        self.horizontalSlider_z = QtWidgets.QSlider(self.frame_Base)
        self.horizontalSlider_z.setMaximum(100)
        self.horizontalSlider_z.setProperty("value", 50)
        self.horizontalSlider_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_z.setObjectName("horizontalSlider_z")
        self.gridLayout_2.addWidget(self.horizontalSlider_z, 5, 0, 1, 1)
        self.horizontalSlider_y = QtWidgets.QSlider(self.frame_Base)
        self.horizontalSlider_y.setMaximum(100)
        self.horizontalSlider_y.setProperty("value", 50)
        self.horizontalSlider_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_y.setObjectName("horizontalSlider_y")
        self.gridLayout_2.addWidget(self.horizontalSlider_y, 3, 0, 1, 1)
        self.pushButton_x = QtWidgets.QPushButton(self.frame_Base)
        self.pushButton_x.setObjectName("pushButton_x")
        self.gridLayout_2.addWidget(self.pushButton_x, 1, 1, 1, 1)
        self.pushButton_y = QtWidgets.QPushButton(self.frame_Base)
        self.pushButton_y.setObjectName("pushButton_y")
        self.gridLayout_2.addWidget(self.pushButton_y, 3, 1, 1, 1)
        self.pushButton_z = QtWidgets.QPushButton(self.frame_Base)
        self.pushButton_z.setObjectName("pushButton_z")
        self.gridLayout_2.addWidget(self.pushButton_z, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_Base, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_y.setText(_translate("Form", "Y"))
        self.label_x.setText(_translate("Form", "X"))
        self.label_z.setText(_translate("Form", "Z"))
        self.pushButton_x.setText(_translate("Form", "Reset"))
        self.pushButton_y.setText(_translate("Form", "Reset"))
        self.pushButton_z.setText(_translate("Form", "Reset"))
