# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenLMCalibrationWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(643, 532)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 17, 0, 1, 2)
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        self.pushButton_save_calibration = QtWidgets.QPushButton(Form)
        self.pushButton_save_calibration.setObjectName("pushButton_save_calibration")
        self.gridLayout.addWidget(self.pushButton_save_calibration, 15, 0, 1, 2)
        self.pushButton_move_stage = QtWidgets.QPushButton(Form)
        self.pushButton_move_stage.setObjectName("pushButton_move_stage")
        self.gridLayout.addWidget(self.pushButton_move_stage, 6, 0, 1, 2)
        self.doubleSpinBox_dy = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_dy.setMinimum(-10000000.0)
        self.doubleSpinBox_dy.setMaximum(1000000000.0)
        self.doubleSpinBox_dy.setProperty("value", 100.0)
        self.doubleSpinBox_dy.setObjectName("doubleSpinBox_dy")
        self.gridLayout.addWidget(self.doubleSpinBox_dy, 3, 1, 1, 1)
        self.label_y_distance = QtWidgets.QLabel(Form)
        self.label_y_distance.setObjectName("label_y_distance")
        self.gridLayout.addWidget(self.label_y_distance, 3, 0, 1, 1)
        self.pushButton_reset_calibration = QtWidgets.QPushButton(Form)
        self.pushButton_reset_calibration.setObjectName("pushButton_reset_calibration")
        self.gridLayout.addWidget(self.pushButton_reset_calibration, 5, 0, 1, 2)
        self.pushButton_calculate_pretilt = QtWidgets.QPushButton(Form)
        self.pushButton_calculate_pretilt.setObjectName("pushButton_calculate_pretilt")
        self.gridLayout.addWidget(self.pushButton_calculate_pretilt, 8, 0, 1, 2)
        self.label_info = QtWidgets.QLabel(Form)
        self.label_info.setWordWrap(True)
        self.label_info.setObjectName("label_info")
        self.gridLayout.addWidget(self.label_info, 2, 0, 1, 2)
        self.pushButton_move_stage_flat = QtWidgets.QPushButton(Form)
        self.pushButton_move_stage_flat.setObjectName("pushButton_move_stage_flat")
        self.gridLayout.addWidget(self.pushButton_move_stage_flat, 16, 1, 1, 1)
        self.label_move_stage_flat = QtWidgets.QLabel(Form)
        self.label_move_stage_flat.setObjectName("label_move_stage_flat")
        self.gridLayout.addWidget(self.label_move_stage_flat, 16, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_title.setText(_translate("Form", "Calibration"))
        self.pushButton_save_calibration.setText(_translate("Form", "Save Calibration"))
        self.pushButton_move_stage.setText(_translate("Form", "Move Stage"))
        self.label_y_distance.setText(_translate("Form", "Y Distance (um)"))
        self.pushButton_reset_calibration.setText(_translate("Form", "Reset Calibration"))
        self.pushButton_calculate_pretilt.setText(_translate("Form", "Calculate PreTilt"))
        self.label_info.setText(_translate("Form", "TextLabel"))
        self.pushButton_move_stage_flat.setText(_translate("Form", "Move Flat to Beam"))
        self.label_move_stage_flat.setText(_translate("Form", "TextLabel"))
