# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenLMCalibrationWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(643, 532)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        self.label_cum_dz_corrected = QtWidgets.QLabel(Form)
        self.label_cum_dz_corrected.setObjectName("label_cum_dz_corrected")
        self.gridLayout.addWidget(self.label_cum_dz_corrected, 4, 1, 1, 1)
        self.label_dpretilt = QtWidgets.QLabel(Form)
        self.label_dpretilt.setObjectName("label_dpretilt")
        self.gridLayout.addWidget(self.label_dpretilt, 10, 1, 1, 1)
        self.label_objective_finish = QtWidgets.QLabel(Form)
        self.label_objective_finish.setObjectName("label_objective_finish")
        self.gridLayout.addWidget(self.label_objective_finish, 8, 1, 1, 1)
        self.label_cum_dy_corrected = QtWidgets.QLabel(Form)
        self.label_cum_dy_corrected.setObjectName("label_cum_dy_corrected")
        self.gridLayout.addWidget(self.label_cum_dy_corrected, 4, 0, 1, 1)
        self.pushButton_save_calibration = QtWidgets.QPushButton(Form)
        self.pushButton_save_calibration.setObjectName("pushButton_save_calibration")
        self.gridLayout.addWidget(self.pushButton_save_calibration, 16, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 17, 0, 1, 2)
        self.label_objective_start = QtWidgets.QLabel(Form)
        self.label_objective_start.setObjectName("label_objective_start")
        self.gridLayout.addWidget(self.label_objective_start, 8, 0, 1, 1)
        self.pushButton_calculate_pretilt = QtWidgets.QPushButton(Form)
        self.pushButton_calculate_pretilt.setObjectName("pushButton_calculate_pretilt")
        self.gridLayout.addWidget(self.pushButton_calculate_pretilt, 9, 0, 1, 2)
        self.label_pretilt = QtWidgets.QLabel(Form)
        self.label_pretilt.setObjectName("label_pretilt")
        self.gridLayout.addWidget(self.label_pretilt, 10, 0, 1, 1)
        self.doubleSpinBox_dy = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_dy.setMinimum(-10000000.0)
        self.doubleSpinBox_dy.setMaximum(1000000000.0)
        self.doubleSpinBox_dy.setProperty("value", 10.0)
        self.doubleSpinBox_dy.setObjectName("doubleSpinBox_dy")
        self.gridLayout.addWidget(self.doubleSpinBox_dy, 2, 1, 1, 1)
        self.pushButton_reset_calibration = QtWidgets.QPushButton(Form)
        self.pushButton_reset_calibration.setObjectName("pushButton_reset_calibration")
        self.gridLayout.addWidget(self.pushButton_reset_calibration, 1, 0, 1, 2)
        self.label_y_distance = QtWidgets.QLabel(Form)
        self.label_y_distance.setObjectName("label_y_distance")
        self.gridLayout.addWidget(self.label_y_distance, 2, 0, 1, 1)
        self.pushButton_move_stage = QtWidgets.QPushButton(Form)
        self.pushButton_move_stage.setObjectName("pushButton_move_stage")
        self.gridLayout.addWidget(self.pushButton_move_stage, 7, 0, 1, 2)
        self.label_cum_dy = QtWidgets.QLabel(Form)
        self.label_cum_dy.setObjectName("label_cum_dy")
        self.gridLayout.addWidget(self.label_cum_dy, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_title.setText(_translate("Form", "Calibration"))
        self.label_cum_dz_corrected.setText(_translate("Form", "Z Distance"))
        self.label_dpretilt.setText(_translate("Form", "Change in PreTilt"))
        self.label_objective_finish.setText(_translate("Form", "Objective Position Finish"))
        self.label_cum_dy_corrected.setText(_translate("Form", "Y Distance"))
        self.pushButton_save_calibration.setText(_translate("Form", "Save Calibration"))
        self.label_objective_start.setText(_translate("Form", "Objective Position"))
        self.pushButton_calculate_pretilt.setText(_translate("Form", "Calculate PreTilt"))
        self.label_pretilt.setText(_translate("Form", "Pre Tilt (deg)"))
        self.pushButton_reset_calibration.setText(_translate("Form", "Reset"))
        self.label_y_distance.setText(_translate("Form", "Y Distance (um)"))
        self.pushButton_move_stage.setText(_translate("Form", "Move Stage"))
        self.label_cum_dy.setText(_translate("Form", "TextLabel"))
