# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenLMCoordinateWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_move_to_position = QtWidgets.QPushButton(Form)
        self.pushButton_move_to_position.setObjectName("pushButton_move_to_position")
        self.gridLayout.addWidget(self.pushButton_move_to_position, 7, 0, 1, 3)
        self.pushButton_remove_coordinate = QtWidgets.QPushButton(Form)
        self.pushButton_remove_coordinate.setObjectName("pushButton_remove_coordinate")
        self.gridLayout.addWidget(self.pushButton_remove_coordinate, 2, 1, 1, 1)
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 1)
        self.comboBox_move_to_system = QtWidgets.QComboBox(Form)
        self.comboBox_move_to_system.setObjectName("comboBox_move_to_system")
        self.gridLayout.addWidget(self.comboBox_move_to_system, 6, 1, 1, 1)
        self.pushButton_add_coordinate = QtWidgets.QPushButton(Form)
        self.pushButton_add_coordinate.setObjectName("pushButton_add_coordinate")
        self.gridLayout.addWidget(self.pushButton_add_coordinate, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 2)
        self.comboBox_positions = QtWidgets.QComboBox(Form)
        self.comboBox_positions.setObjectName("comboBox_positions")
        self.gridLayout.addWidget(self.comboBox_positions, 6, 2, 1, 1)
        self.label_position_list = QtWidgets.QLabel(Form)
        self.label_position_list.setObjectName("label_position_list")
        self.gridLayout.addWidget(self.label_position_list, 6, 0, 1, 1)
        self.pushButton_save_coordinate = QtWidgets.QPushButton(Form)
        self.pushButton_save_coordinate.setObjectName("pushButton_save_coordinate")
        self.gridLayout.addWidget(self.pushButton_save_coordinate, 2, 2, 1, 1)
        self.label_coordinate_list = QtWidgets.QLabel(Form)
        self.label_coordinate_list.setObjectName("label_coordinate_list")
        self.gridLayout.addWidget(self.label_coordinate_list, 3, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_move_to_position.setText(_translate("Form", "Move To Position"))
        self.pushButton_remove_coordinate.setText(_translate("Form", "Remove Position"))
        self.label_title.setText(_translate("Form", "Experiment Positions"))
        self.pushButton_add_coordinate.setText(_translate("Form", "Add Position"))
        self.label_position_list.setText(_translate("Form", "Selected Position"))
        self.pushButton_save_coordinate.setText(_translate("Form", "Save Positions"))
        self.label_coordinate_list.setText(_translate("Form", "TextLabel"))
