# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenLMSpinningDiskWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_disk_position = QtWidgets.QLabel(Form)
        self.label_disk_position.setObjectName("label_disk_position")
        self.gridLayout.addWidget(self.label_disk_position, 7, 0, 1, 1)
        self.spinBox_disk_position = QtWidgets.QSpinBox(Form)
        self.spinBox_disk_position.setObjectName("spinBox_disk_position")
        self.gridLayout.addWidget(self.spinBox_disk_position, 7, 1, 1, 1)
        self.pushButton_disk_connect = QtWidgets.QPushButton(Form)
        self.pushButton_disk_connect.setObjectName("pushButton_disk_connect")
        self.gridLayout.addWidget(self.pushButton_disk_connect, 4, 0, 1, 2)
        self.comboBox_disk_type = QtWidgets.QComboBox(Form)
        self.comboBox_disk_type.setObjectName("comboBox_disk_type")
        self.gridLayout.addWidget(self.comboBox_disk_type, 1, 1, 1, 1)
        self.spinBox_disk_emission_filter = QtWidgets.QSpinBox(Form)
        self.spinBox_disk_emission_filter.setObjectName("spinBox_disk_emission_filter")
        self.gridLayout.addWidget(self.spinBox_disk_emission_filter, 8, 1, 1, 1)
        self.label_disk_status = QtWidgets.QLabel(Form)
        self.label_disk_status.setObjectName("label_disk_status")
        self.gridLayout.addWidget(self.label_disk_status, 10, 0, 1, 2)
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        self.pushButton_disk_apply = QtWidgets.QPushButton(Form)
        self.pushButton_disk_apply.setObjectName("pushButton_disk_apply")
        self.gridLayout.addWidget(self.pushButton_disk_apply, 9, 0, 1, 2)
        self.label_disk_emission_filter = QtWidgets.QLabel(Form)
        self.label_disk_emission_filter.setObjectName("label_disk_emission_filter")
        self.gridLayout.addWidget(self.label_disk_emission_filter, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 2)
        self.label_disk_type = QtWidgets.QLabel(Form)
        self.label_disk_type.setObjectName("label_disk_type")
        self.gridLayout.addWidget(self.label_disk_type, 1, 0, 1, 1)
        self.checkBox_disk_onoff = QtWidgets.QCheckBox(Form)
        self.checkBox_disk_onoff.setObjectName("checkBox_disk_onoff")
        self.gridLayout.addWidget(self.checkBox_disk_onoff, 6, 0, 1, 1)
        self.comboBox_disk_mode = QtWidgets.QComboBox(Form)
        self.comboBox_disk_mode.setObjectName("comboBox_disk_mode")
        self.gridLayout.addWidget(self.comboBox_disk_mode, 5, 1, 1, 1)
        self.label_disk_mode = QtWidgets.QLabel(Form)
        self.label_disk_mode.setObjectName("label_disk_mode")
        self.gridLayout.addWidget(self.label_disk_mode, 5, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_disk_position.setText(_translate("Form", "Disk Position"))
        self.pushButton_disk_connect.setText(_translate("Form", "Connect"))
        self.label_disk_status.setText(_translate("Form", "Status"))
        self.label_title.setText(_translate("Form", "Spinning Disk"))
        self.pushButton_disk_apply.setText(_translate("Form", "Apply Settings"))
        self.label_disk_emission_filter.setText(_translate("Form", "Emission Filter"))
        self.label_disk_type.setText(_translate("Form", "Disk Type"))
        self.checkBox_disk_onoff.setText(_translate("Form", "Disk On"))
        self.label_disk_mode.setText(_translate("Form", "Mode"))
