# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenLMDetectorWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(405, 398)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_resolution_y = QtWidgets.QSpinBox(Form)
        self.spinBox_resolution_y.setMaximum(1000000000)
        self.spinBox_resolution_y.setObjectName("spinBox_resolution_y")
        self.gridLayout.addWidget(self.spinBox_resolution_y, 4, 2, 1, 1)
        self.label_resolution = QtWidgets.QLabel(Form)
        self.label_resolution.setObjectName("label_resolution")
        self.gridLayout.addWidget(self.label_resolution, 4, 0, 1, 1)
        self.comboBox_trigger_source = QtWidgets.QComboBox(Form)
        self.comboBox_trigger_source.setObjectName("comboBox_trigger_source")
        self.gridLayout.addWidget(self.comboBox_trigger_source, 5, 1, 1, 2)
        self.comboBox_exposure_mode = QtWidgets.QComboBox(Form)
        self.comboBox_exposure_mode.setObjectName("comboBox_exposure_mode")
        self.gridLayout.addWidget(self.comboBox_exposure_mode, 7, 1, 1, 2)
        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 1, 0, 1, 1)
        self.label_trigger_source = QtWidgets.QLabel(Form)
        self.label_trigger_source.setObjectName("label_trigger_source")
        self.gridLayout.addWidget(self.label_trigger_source, 5, 0, 1, 1)
        self.label_exposure_mode = QtWidgets.QLabel(Form)
        self.label_exposure_mode.setObjectName("label_exposure_mode")
        self.gridLayout.addWidget(self.label_exposure_mode, 7, 0, 1, 1)
        self.label_pixelsize = QtWidgets.QLabel(Form)
        self.label_pixelsize.setObjectName("label_pixelsize")
        self.gridLayout.addWidget(self.label_pixelsize, 3, 0, 1, 1)
        self.lineEdit_detector_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_detector_name.setObjectName("lineEdit_detector_name")
        self.gridLayout.addWidget(self.lineEdit_detector_name, 1, 1, 1, 2)
        self.label_trigger_edge = QtWidgets.QLabel(Form)
        self.label_trigger_edge.setObjectName("label_trigger_edge")
        self.gridLayout.addWidget(self.label_trigger_edge, 6, 0, 1, 1)
        self.comboBox_trigger_edge = QtWidgets.QComboBox(Form)
        self.comboBox_trigger_edge.setObjectName("comboBox_trigger_edge")
        self.gridLayout.addWidget(self.comboBox_trigger_edge, 6, 1, 1, 2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 3)
        self.doubleSpinBox_pixelsize = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_pixelsize.setDecimals(2)
        self.doubleSpinBox_pixelsize.setMinimum(1.0)
        self.doubleSpinBox_pixelsize.setMaximum(10000.0)
        self.doubleSpinBox_pixelsize.setSingleStep(0.01)
        self.doubleSpinBox_pixelsize.setObjectName("doubleSpinBox_pixelsize")
        self.gridLayout.addWidget(self.doubleSpinBox_pixelsize, 3, 1, 1, 2)
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 3)
        self.pushButton_apply_detector_settings = QtWidgets.QPushButton(Form)
        self.pushButton_apply_detector_settings.setObjectName("pushButton_apply_detector_settings")
        self.gridLayout.addWidget(self.pushButton_apply_detector_settings, 8, 0, 1, 3)
        self.spinBox_resolution_x = QtWidgets.QSpinBox(Form)
        self.spinBox_resolution_x.setMaximum(1000000)
        self.spinBox_resolution_x.setObjectName("spinBox_resolution_x")
        self.gridLayout.addWidget(self.spinBox_resolution_x, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_resolution.setText(_translate("Form", "Resolution"))
        self.label_name.setText(_translate("Form", "Name"))
        self.label_trigger_source.setText(_translate("Form", "Trigger Source"))
        self.label_exposure_mode.setText(_translate("Form", "Exposure Mode"))
        self.label_pixelsize.setText(_translate("Form", "Pixel Size (um)"))
        self.label_trigger_edge.setText(_translate("Form", "Trigger Edge"))
        self.label_title.setText(_translate("Form", "Detector"))
        self.pushButton_apply_detector_settings.setText(_translate("Form", "Apply Detector Settings"))
