# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CLEMImageWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(308, 281)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 2)
        self.comboBox_imaging_mode = QtWidgets.QComboBox(Form)
        self.comboBox_imaging_mode.setObjectName("comboBox_imaging_mode")
        self.gridLayout.addWidget(self.comboBox_imaging_mode, 3, 1, 1, 1)
        self.label_imaging_mode = QtWidgets.QLabel(Form)
        self.label_imaging_mode.setObjectName("label_imaging_mode")
        self.gridLayout.addWidget(self.label_imaging_mode, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 2)
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 2)
        self.doubleSpinBox_exposure = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_exposure.setDecimals(4)
        self.doubleSpinBox_exposure.setMinimum(0.001)
        self.doubleSpinBox_exposure.setMaximum(10000000.0)
        self.doubleSpinBox_exposure.setSingleStep(0.001)
        self.doubleSpinBox_exposure.setObjectName("doubleSpinBox_exposure")
        self.gridLayout.addWidget(self.doubleSpinBox_exposure, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 2)
        self.label_exposure = QtWidgets.QLabel(Form)
        self.label_exposure.setObjectName("label_exposure")
        self.gridLayout.addWidget(self.label_exposure, 1, 0, 1, 1)
        self.label_imaging_format = QtWidgets.QLabel(Form)
        self.label_imaging_format.setObjectName("label_imaging_format")
        self.gridLayout.addWidget(self.label_imaging_format, 2, 0, 1, 1)
        self.pushButton_acquire_image = QtWidgets.QPushButton(Form)
        self.pushButton_acquire_image.setObjectName("pushButton_acquire_image")
        self.gridLayout.addWidget(self.pushButton_acquire_image, 8, 0, 1, 2)
        self.comboBox_imaging_format = QtWidgets.QComboBox(Form)
        self.comboBox_imaging_format.setObjectName("comboBox_imaging_format")
        self.gridLayout.addWidget(self.comboBox_imaging_format, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Objective Stage: N/A"))
        self.label_imaging_mode.setText(_translate("Form", "Mode"))
        self.label.setText(_translate("Form", "Detector: N/A"))
        self.label_title.setText(_translate("Form", "Imaging"))
        self.label_2.setText(_translate("Form", "Laser Controller: N/A"))
        self.label_exposure.setText(_translate("Form", "Exposure (ms)"))
        self.label_imaging_format.setText(_translate("Form", "Format"))
        self.pushButton_acquire_image.setText(_translate("Form", "PushButton"))
