# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CLEMObjectiveWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(406, 387)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_absolute_position = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_absolute_position.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_absolute_position.setMinimum(-100000000.0)
        self.doubleSpinBox_absolute_position.setMaximum(1000000000.0)
        self.doubleSpinBox_absolute_position.setObjectName("doubleSpinBox_absolute_position")
        self.gridLayout.addWidget(self.doubleSpinBox_absolute_position, 5, 0, 1, 2)
        self.doubleSpinBox_saved_position = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_saved_position.setMinimum(-1000000000.0)
        self.doubleSpinBox_saved_position.setMaximum(10000000000.0)
        self.doubleSpinBox_saved_position.setObjectName("doubleSpinBox_saved_position")
        self.gridLayout.addWidget(self.doubleSpinBox_saved_position, 2, 1, 1, 1)
        self.pushButton_move_relative_down = QtWidgets.QPushButton(Form)
        self.pushButton_move_relative_down.setObjectName("pushButton_move_relative_down")
        self.gridLayout.addWidget(self.pushButton_move_relative_down, 10, 0, 1, 1)
        self.pushButton_get_position = QtWidgets.QPushButton(Form)
        self.pushButton_get_position.setObjectName("pushButton_get_position")
        self.gridLayout.addWidget(self.pushButton_get_position, 3, 0, 1, 1)
        self.pushButton_save_position = QtWidgets.QPushButton(Form)
        self.pushButton_save_position.setObjectName("pushButton_save_position")
        self.gridLayout.addWidget(self.pushButton_save_position, 3, 1, 1, 1)
        self.label_absolute_position = QtWidgets.QLabel(Form)
        self.label_absolute_position.setObjectName("label_absolute_position")
        self.gridLayout.addWidget(self.label_absolute_position, 4, 0, 1, 2)
        self.pushButton_move_relative_up = QtWidgets.QPushButton(Form)
        self.pushButton_move_relative_up.setObjectName("pushButton_move_relative_up")
        self.gridLayout.addWidget(self.pushButton_move_relative_up, 10, 1, 1, 1)
        self.label_relative_position = QtWidgets.QLabel(Form)
        self.label_relative_position.setObjectName("label_relative_position")
        self.gridLayout.addWidget(self.label_relative_position, 7, 0, 1, 2)
        self.label_current_position = QtWidgets.QLabel(Form)
        self.label_current_position.setObjectName("label_current_position")
        self.gridLayout.addWidget(self.label_current_position, 1, 0, 1, 1)
        self.label_saved_position = QtWidgets.QLabel(Form)
        self.label_saved_position.setObjectName("label_saved_position")
        self.gridLayout.addWidget(self.label_saved_position, 2, 0, 1, 1)
        self.doubleSpinBox_relative_position = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_relative_position.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_relative_position.setMinimum(-100000000.0)
        self.doubleSpinBox_relative_position.setMaximum(1000000000.0)
        self.doubleSpinBox_relative_position.setObjectName("doubleSpinBox_relative_position")
        self.gridLayout.addWidget(self.doubleSpinBox_relative_position, 8, 0, 1, 2)
        self.doubleSpinBox_current_position = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_current_position.setMinimum(-10000000000.0)
        self.doubleSpinBox_current_position.setMaximum(100000000.0)
        self.doubleSpinBox_current_position.setObjectName("doubleSpinBox_current_position")
        self.gridLayout.addWidget(self.doubleSpinBox_current_position, 1, 1, 1, 1)
        self.pushButton_move_absolute = QtWidgets.QPushButton(Form)
        self.pushButton_move_absolute.setObjectName("pushButton_move_absolute")
        self.gridLayout.addWidget(self.pushButton_move_absolute, 6, 0, 1, 2)
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_move_relative_down.setText(_translate("Form", "Move Down"))
        self.pushButton_get_position.setText(_translate("Form", "Get Position"))
        self.pushButton_save_position.setText(_translate("Form", "Save Position"))
        self.label_absolute_position.setText(_translate("Form", "Absolute Movement"))
        self.pushButton_move_relative_up.setText(_translate("Form", "Move Up"))
        self.label_relative_position.setText(_translate("Form", "Relative Movement"))
        self.label_current_position.setText(_translate("Form", "Current Position (um)"))
        self.label_saved_position.setText(_translate("Form", "Saved Position (um)"))
        self.pushButton_move_absolute.setText(_translate("Form", "Move to Position"))
        self.label_title.setText(_translate("Form", "ObjectiveStage"))
